logging:
  level:
    com.example: debug
ldapchamp:
  dn-key: entryDN
  url: ldap://10.10.10.201:10389
  base: DC=example,DC=com
  user-dn: cn=jsmith,ou=users,dc=example,dc=com
  password: password
  ignore-partial-result-exception: true
  dn-replacements: entryDN,distinguishedName
  skipped-properties: userPassword
server:
  port: 8080
